# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your Azure Functions project
  DOTNET_VERSION: '8.0.x' # .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet restore
          popd

      - name: Build project
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet build --configuration Release --output ./output
          popd

      - name: Publish project
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet publish --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Service principal credentials in JSON format

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'HmacFunction240727' # Name of your Azure Function App
          slot-name: 'Production' # Slot name (default is Production)
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

